# Generated by Django 5.1.15 on 2026-05-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=600)),
                ('Satus', models.CharField(choices=[('notstarted', 'Not Started'), ('inprogress', 'In Progress'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], max_length=600)),
                ('deadline', models.DateField()),
                ('Tier', models.CharField(choices=[('reach', 'Reach'), ('match', 'Match'), ('safety', 'Safety')], max_length=600)),
            ],
        ),
    ]
