# Generated by Django 5.1.15 on 2026-05-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=600)),
                ('City', models.CharField(max_length=600)),
                ('School', models.CharField(max_length=600)),
                ('OverallGPA', models.FloatField(max_length=4)),
                ('FreshGPAUW', models.FloatField(max_length=4)),
                ('FreshGPAU', models.FloatField(max_length=4)),
                ('SophGPAUW', models.FloatField(max_length=4)),
                ('SophGPAW', models.FloatField(max_length=4)),
                ('JunGPAUW', models.FloatField(max_length=4)),
                ('JunGPAW', models.FloatField(max_length=4)),
                ('SenGPAUW', models.FloatField(max_length=4)),
                ('SenGPAW', models.FloatField(max_length=4)),
                ('SAT', models.IntegerField(max_length=4)),
                ('ACT', models.IntegerField(max_length=2)),
                ('Activity1', models.CharField(max_length=100)),
                ('Description1', models.CharField(max_length=150)),
                ('Activity2', models.CharField(max_length=100)),
                ('Description2', models.CharField(max_length=150)),
                ('Activity3', models.CharField(max_length=100)),
                ('Description3', models.CharField(max_length=150)),
                ('Activity4', models.CharField(max_length=100)),
                ('Description4', models.CharField(max_length=150)),
                ('Activity5', models.CharField(max_length=100)),
                ('Description5', models.CharField(max_length=150)),
                ('Activity6', models.CharField(max_length=100)),
                ('Description6', models.CharField(max_length=150)),
                ('Activity7', models.CharField(max_length=100)),
                ('Description7', models.CharField(max_length=150)),
                ('Activity8', models.CharField(max_length=100)),
                ('Description8', models.CharField(max_length=150)),
                ('Activity9', models.CharField(max_length=100)),
                ('Description9', models.CharField(max_length=150)),
                ('Activity10', models.CharField(max_length=100)),
                ('Description10', models.CharField(max_length=150)),
                ('Teacher1', models.CharField(max_length=100)),
                ('Teacher2', models.CharField(max_length=100)),
                ('Teacher3', models.CharField(max_length=100)),
                ('Teacher4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='APScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(choices=[('AP Art and Design', 'AP Art and Design'), ('AP Art History', 'AP Art History'), ('AP Music Theory', 'AP Music Theory'), ('AP English Language and Composition', 'AP English Language and Composition'), ('AP English Literature and Composition', 'AP English Literature and Composition'), ('AP African American Studies', 'AP African American Studies'), ('AP Comparative Government and Politics', 'AP Comparative Government and Politics'), ('AP European History', 'AP European History'), ('AP Human Geography', 'AP Human Geography'), ('AP Macroeconomics', 'AP Macroeconomics'), ('AP Microeconomics', 'AP Microeconomics'), ('AP Psychology', 'AP Psychology'), ('AP United States Government and Politics', 'AP United States Government and Politics'), ('AP United States History', 'AP United States History'), ('AP World History: Modern', 'AP World History: Modern'), ('AP Calculus AB', 'AP Calculus AB'), ('AP Calculus BC', 'AP Calculus BC'), ('AP Computer Science A', 'AP Computer Science A'), ('AP Computer Science Principles', 'AP Computer Science Principles'), ('AP Precalculus', 'AP Precalculus'), ('AP Statistics', 'AP Statistics'), ('AP Biology', 'AP Biology'), ('AP Chemistry', 'AP Chemistry'), ('AP Environmental Science', 'AP Environmental Science'), ('AP Physics 1', 'AP Physics 1: Algebra-Based'), ('AP Physics 2', 'AP Physics 2: Algebra-Based'), ('AP Physics C E&M', 'AP Physics C: Electricity and Magnetism'), ('AP Physics C Mechanics', 'AP Physics C: Mechanics'), ('AP Chinese Language and Culture', 'AP Chinese Language and Culture'), ('AP French Language and Culture', 'AP French Language and Culture'), ('AP German Language and Culture', 'AP German Language and Culture'), ('AP Italian Language and Culture', 'AP Italian Language and Culture'), ('AP Japanese Language and Culture', 'AP Japanese Language and Culture'), ('AP Latin', 'AP Latin'), ('AP Spanish Language and Culture', 'AP Spanish Language and Culture'), ('AP Spanish Literature and Culture', 'AP Spanish Literature and Culture'), ('AP Research', 'AP Research'), ('AP Seminar', 'AP Seminar'), ('AP Business with Personal Finance', 'AP Business with Personal Finance'), ('AP Cybersecurity', 'AP Cybersecurity')], max_length=100)),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_scores', to='Tracker.userprofile')),
            ],
        ),
    ]
