# Generated by Django 5.1.15 on 2026-05-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_userprofile_user_alter_apscore_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Award1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Award2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Award3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Award4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Award5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
