# Generated by Django 5.1.15 on 2026-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_userprofile_award1_userprofile_award2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='OverallGPA',
            new_name='OverallGPAUW',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='OverallGPAW',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
