# Generated by Django 5.1.15 on 2026-05-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_rename_overallgpa_userprofile_overallgpauw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pref_area',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
