# Generated by Django 5.1.15 on 2026-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_userprofile_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='likleyhood',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
