# Generated by Django 5.1.15 on 2026-05-11 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_colleges_likleyhood'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colleges',
            name='likleyhood',
        ),
        migrations.AddField(
            model_name='colleges',
            name='deadline_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colleges',
            name='likelihood',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='colleges',
            name='major',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='colleges',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='colleges',
            name='portal_url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='colleges',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='Satus',
            field=models.CharField(choices=[('notstarted', 'Not Started'), ('inprogress', 'In Progress'), ('submitted', 'Submitted'), ('deferred', 'Deferred'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected')], default='notstarted', max_length=600),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
