# Generated by Django 5.1.15 on 2026-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0009_remove_colleges_likleyhood_colleges_deadline_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='deadline_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='likelihood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description10',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description6',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description7',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description8',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Description9',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
