# Generated by Django 5.1.15 on 2026-05-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_alter_colleges_deadline_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_status',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
