# List of common colleges
US_COLLEGES = [
    "Harvard University", "Stanford University", "Massachusetts Institute of Technology",
    "Yale University", "Princeton University", "Columbia University", "Brown University",
    "Cornell University", "Dartmouth College", "University of Pennsylvania",
    "Duke University", "Northwestern University", "Johns Hopkins University",
    "University of Chicago", "Vanderbilt University", "Rice University",
    "Washington University in St. Louis", "Emory University", "Georgetown University",
    "Carnegie Mellon University", "University of Notre Dame", "Tufts University",
    "Wake Forest University", "Boston College", "Boston University",
    "New York University", "Northeastern University", "University of Southern California",
    "University of California, Berkeley", "University of California, Los Angeles",
    "University of California, San Diego", "University of California, Davis",
    "University of California, Irvine", "University of California, Santa Barbara",
    "University of California, Santa Cruz", "University of California, Riverside",
    "University of California, Merced", "California Institute of Technology",
    "Pomona College", "Claremont McKenna College", "Harvey Mudd College",
    "Scripps College", "Pitzer College", "Occidental College", "Loyola Marymount University",
    "University of Michigan", "Michigan State University", "University of Illinois Urbana-Champaign",
    "University of Wisconsin-Madison", "University of Minnesota Twin Cities",
    "Ohio State University", "Ohio University", "University of Cincinnati",
    "Indiana University Bloomington", "Purdue University", "University of Iowa",
    "Iowa State University", "University of Missouri", "University of Kansas",
    "University of Nebraska-Lincoln", "University of Oklahoma", "University of Texas at Austin",
    "Texas A&M University", "Rice University", "Southern Methodist University",
    "University of Houston", "Baylor University", "Texas Christian University",
    "University of Florida", "Florida State University", "University of Miami",
    "University of Central Florida", "University of South Florida",
    "University of Georgia", "Georgia Institute of Technology", "Emory University",
    "University of North Carolina at Chapel Hill", "Duke University", "North Carolina State University",
    "Wake Forest University", "University of Virginia", "Virginia Tech", "William & Mary",
    "University of Maryland, College Park", "Johns Hopkins University",
    "Pennsylvania State University", "University of Pittsburgh", "Temple University",
    "Drexel University", "Lehigh University", "Bucknell University", "Villanova University",
    "Rutgers University", "Princeton University", "Stevens Institute of Technology",
    "University of Washington", "Washington State University", "University of Oregon",
    "Oregon State University", "University of Colorado Boulder", "Colorado State University",
    "University of Utah", "Arizona State University", "University of Arizona",
    "University of Nevada, Las Vegas", "University of Hawaii at Manoa",
    "University of Connecticut", "University of Massachusetts Amherst", "UMass Lowell",
    "Boston College", "Tufts University", "Brandeis University", "Bentley University",
    "Williams College", "Amherst College", "Wellesley College", "Smith College",
    "Mount Holyoke College", "Bowdoin College", "Bates College", "Colby College",
    "Middlebury College", "Hamilton College", "Colgate University", "Vassar College",
    "Swarthmore College", "Haverford College", "Bryn Mawr College",
    "Rochester Institute of Technology", "University of Rochester",
    "Syracuse University", "SUNY Buffalo", "Stony Brook University", "Binghamton University",
    "Santa Clara University", "San Diego State University", "San Jose State University",
    "California Polytechnic State University, San Luis Obispo",
    "Case Western Reserve University", "DePaul University", "Loyola University Chicago",
    "Marquette University", "Saint Louis University", "University of Denver",
    "Tulane University", "University of Tulsa",
    "Bowling Green State University", "Kent State University", "University of Toledo",
    "Cleveland State University", "Wright State University", "Youngstown State University",
    "Miami University", "Xavier University", "University of Dayton",
]